name: activity_app
version: "0.0.1-dev.0"
description: surf onboarding app by dshevchenko
publish_to: none

dependencies:
  dio: ^4.0.4
  elementary: ^1.1.0
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_native_splash: ^2.1.1
  flutter_svg: ^1.0.3
  logger: ^1.1.0
  provider: ^6.0.1
  retrofit: ^3.0.0

  surf_logger: ^1.0.1

dev_dependencies:
  build_runner: ^2.1.5
  dart_code_metrics: ^4.7.0
  elementary_test: ^1.0.1
  flutter_test:
    sdk: flutter
  json_serializable: ^6.1.1
  retrofit_generator: ^3.0.0
  surf_lint_rules: ^1.4.1

environment:
  sdk: ">=2.14.0-0 <3.0.0"

flutter:
  uses-material-design: true
  assets:
    - assets/fonts/
    - assets/icons/
    - assets/images/
